### ISSUE TITLE
Syntax error project.py

### ISSUE THREAD

**Issue by 4FCG** [AdamantLife/Gwern2DeepDanbooru#4]
After installing with
`pip install git+https://github.com/AdamantLife/Gwern2DeepDanbooru`

When running
`python -m Gwern2DeepDanbooru run`

Error
`Traceback (most recent call last):
  File "C:\Python38\lib\runpy.py", line 185, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "C:\Python38\lib\runpy.py", line 144, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "C:\Python38\lib\runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "C:\Python38\lib\site-packages\Gwern2DeepDanbooru\__init__.py", line 26, in <module>
    from Gwern2DeepDanbooru import utils, gwern, project
  File "C:\Python38\lib\site-packages\Gwern2DeepDanbooru\project.py", line 95
    def get_metadata_by_id(self, _id, , rowid = False, db = None):
                                      ^
SyntaxError: invalid syntax`

**Comment by AdamantLife** [comment]
Thanks for opening the issue, code fixed with most recent pull
